config/routes.rb
Rails.application.routes.draw do

  # 卍関連
  get '/posts/:reply_id/new' => 'posts#new'
  post '/posts/select' => 'posts#select'
  post '/posts' => 'posts#create'
  post '/posts' => 'posts#update'
  get "/posts/:id/show" => "posts#show"
  get '/posts/:type/index' => 'posts#index'
  post '/posts/:type/index' => 'posts#index'
  post '/posts/:question_id/:ans_id' => 'posts#bestanswer'

  #いいね
  post '/likes/:post_id/:type/create' => 'likes#create'
  post '/likes/:post_id/:type/destroy' => 'likes#destroy'

  # ユーザー関連
  get '/login' => 'users#login_form'
  get '/signup' => 'users#signup_form'
  post '/login' => 'users#login'
  post '/create' => 'users#create'
  post '/logout' => 'users#logout'
  get '/users/edit' => 'users#edit'
  post '/users/update' => 'users#update'
  get "/users/:id/show" => "users#show"

  #通知
  post '/notice/looked' => 'notice#looked'

  get '/' => 'home#top'
  get '/' => 'application#set_current_user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/notification.rb
class Notification < ApplicationRecord
    def post
        return Post.find_by(id: self.post_id)
    end

    def user
        return User.find_by(id: self.do_user_id)
    end
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content, {presence: true}

    enum tag:{
        notType: 0,
        information: 1,
        gaiji: 2,
        question: 3,
        edit: 4,
    }

    def user
        return User.find_by(id: self.user_id)
    end

    def like_count
        return Like.where(post_id: self.id).count
    end

    def like_member_random
        @list = Like.where(post_id: self.id)
        @count = @list.count
        @user_id = @list.last.user_id
        return User.find_by(id: @user_id).name
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user, :get_user_notifications

    def set_current_user
        @current_user = User.find_by(id: session[:user_id]);
    end

    def get_user_notifications
        @notifications = Notification.where(post_user_id: session[:user_id])
        @new_notice = @notifications.where(is_looked: false)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_current_user

  def top
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        @post_id = params[:post_id]
        @like = Like.new(user_id:@current_user.id,post_id:@post_id)
        @like.save
        @post =  Post.find_by(id:@post_id)
        if Notification.find_by(post_id:@post_id,do_user_id: @current_user.id) == nil
            @notice = Notification.new(post_id:@post_id, post_user_id: @post.user_id, do_user_id: @current_user.id, is_looked: false)
            @notice.save
        end
        if params[:type] == 'edit'
            redirect_to("/posts/#{@post_id}/show")
            return    
        end
        redirect_to("/posts/notType/index")
    end

    def destroy
        @like = Like.find_by(user_id:@current_user.id,post_id:params[:post_id])
        @like.destroy
        @post_id = params[:post_id]
        @post =  Post.find_by(id:@post_id)
        @notice = Notification.new(post_id:@post_id, post_user_id: @post.user_id, do_user_id: @current_user.id, is_looked: false)
        if params[:type] == 'edit'
            redirect_to("/posts/#{@post_id}/show")
            return
        end
        redirect_to("/posts/notType/index")
    end
end

app/controllers/notice_controller.rb
class NoticeController < ApplicationController
    def looked
        @notifications.each do |notice|
            notice.is_looked = true
            notice.save
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @type = params[:type]
        @random = rand(2)
        @posts = Post.all
        if params[:search_word]
            @search_word=params[:search_word]
        end
    end

    def new
        @post = Post.new
        flash[:reply_id] = params[:reply_id]
    end

    def create
        @post=Post.new(user_id: @current_user.id, content: params[:post][:content], tag: params[:post][:tag])

        if params[:post][:input_image_name_1]
            image = params[:post][:input_image_name_1]
            @post.image_1="#{SecureRandom.uuid}.jpg"
            File.binwrite("public/images/tweet_images/#{@post.image_1}", image.read)           
        end
        if params[:post][:input_image_name_2]
            image = params[:post][:input_image_name_2]
            @post.image_2="#{SecureRandom.uuid}.jpg"
            File.binwrite("public/images/tweet_images/#{@post.image_2}", image.read)           
        end
        if params[:post][:input_image_name_3]
            image = params[:post][:input_image_name_3]
            @post.image_3="#{SecureRandom.uuid}.jpg"
            File.binwrite("public/images/tweet_images/#{@post.image_3}", image.read)           
        end
        if params[:post][:input_image_name_4]
            image = params[:post][:input_image_name_4]
            @post.image_4="#{SecureRandom.uuid}.jpg"
            File.binwrite("public/images/tweet_images/#{@post.image_4}", image.read)           
        end
        if flash[:reply_id]
            @post.reply_id = flash[:reply_id]

        end
        if @post.save
            flash[:notice]="せーの！卍まんじ卍"
            redirect_to("/posts/question/index")
        else
            render("/posts/new")
        end


    end
    def select
        @type = params[:tag]
        redirect_to("/posts/#{@type}/index")
    end

    def update
    end

    def show
        @post = Post.find_by(id: params[:id])
        @reply_posts = Post.where(reply_id: @post.id)
        @type = 'edit'
    end

    def bestanswer
        @ques_post = Post.find_by(id: params[:question_id])
        @ans_post = Post.find_by(id: params[:ans_id])
        @ques_post.best_answer_post_id = @ans_post.id;
        @ques_post.save
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def login_form
    
  end

  def signup_form

  end

  def create
    @user = User.new(
      name: params[:name],
      password: params[:password],
      icon_image: "defult.jpg"
    )

    if @user && @user.save
      session[:user_id]=@user.id
      flash[:notice]="新規登録しました"
      redirect_to("/")
    else
      render("users/signup_form")
    end
  end

  def login
    @user = User.find_by(
      name: params[:name]
    )

    if @user && @user.authenticate(params[:password])
      session[:user_id]=@user.id
      flash[:notice]="ログインしました"
      redirect_to("/")
    else
      render("users/login_form")
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to("/login")
  end

  def edit
    @user = User.find_by(id: @current_user.id)
  end

  def update
    @user = User.find_by(id: @current_user.id)
    if params[:icon]
      @user.icon_image = "#{@user.id}.jpg"
     image = params[:icon]
     File.binwrite("public/images/#{@user.icon_image}", image.read)
    end
    @user.name = params[:name]
    if @user.save
      flash[:notice] = "成功しました"
      @current_user = @user
    end
    redirect_to("/")
  end

  def show
    @user = User.find_by(id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notice_helper.rb
module NoticeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class='title-wrapper'>
    <div class='title'>
        <h1>ようこそオドッターへ</h1>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Odo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="content-type" charset="utf-8">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
	  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
    <script src="//code.jquery.com/jquery-1.12.1.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <header>
      <div class="header-outerFrame">
        <div class="header-outerFrame-item1"><!- 外枠の子1 -->
            <%= form_with(url:"/posts/notType/index",method: :get,local: true) do |f| %>
                <%= f.text_field :search_word %>
                <%= f.submit "検索" %>
            <%end%>
        </div>
        <div class="header-outerFrame-item3"><!- 外枠の子2 -->
            <p><%= link_to("odotter","/",class: "header-odotter-letter") %></p>
        </div>
            <div class="header-outerFrame-item3"><!- 外枠の子3 -->
            <% if @current_user == nil %>
              <p class="header-ruledLine common-letterColor-white">|<p/>
              <p><%= link_to("新規登録","/signup",class: "common-letterColor-white") %></p>
              <p class="header-ruledLine common-letterColor-white">|<p/>
              <p><%= link_to("ログイン","/login",class: "common-letterColor-white") %></p>
            <% else %>
              <p class="header-ruledLine common-letterColor-white">|<p/>
              <p><%= link_to("卍一覧","/posts/notType/index",class: "common-letterColor-white") %></p>
              <p class="header-ruledLine common-letterColor-white">|<p/>
              <p><%= link_to("卍する","/posts/0/new",class: "common-letterColor-white") %></p>
              <p class="header-ruledLine common-letterColor-white">|<p/>
              <%= link_to("/notice/looked",method: :post,class: "common-letterColor-white") do %><i class="far fa-bell notice-icon"><%= @new_notice.size %></i><% end %>
              <p class="header-ruledLine common-letterColor-white">|<p/>
                <div class="dialog" id="sample-dialog">
                  <div class="dialog-header">
                    <span class="dialog-title">サンプルダイアログ</span>
                    <button type="button" class="dialog-close">
                      閉じる☓
                    </button>
                  </div>
                  <div class="dialog-content">
                    <p>ダイアログです</p>
                  </div>
                </div>
                <button id="open-sample-dialog">
                    <img class="icon-image" src="<%= "/images/#{@current_user.icon_image}" %>">
                </button>
              <!--<p><%= link_to("ログアウト","/logout",method: :post,class: "common-letterColor-white") %></p>-->
            <% end %>
        </div>
      </div>
    </header>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class="notificationPanel">
      <ul>
        <% @notifications.each do |notice| %>
          <li><%= notice.user.name %>さんがあなたのツイートをいいねしました。<br><%= notice.post.content %></li>
        <% end %>
      <ul>
    </div>
    <%= yield %>
  </body>
</html>

<script type="text/javascript">
$(".notificationPanel").hide();
  var isShow = false;
  $(".notice-icon").click(function () {
    if (isShow){
      $(".notificationPanel").hide();
      isShow = false;
    } else {
      $(".notificationPanel").show();
      isShow = true;
    }
  });
</script>
<script type="text/javascript">
    $("#open-sample-dialog").on("click", function(){
        var leftPosition = (($(window).width() - $("#sample-dialog").outerWidth(true)) / 2);
        $("#sample-dialog").css({"left": leftPosition + "px"});
        $("#sample-dialog").show();
    });
    $(".dialog-close").on("click", function(){
        $(this).parents(".dialog").hide();
    });
</script>
<script type="text/javascript" src="application.js" ></script>

app/views/posts/index.html.erb
<link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
<div class="index-wrapper">
    <div class="manji-list">
        <div class="advertisement-image">
            <%= form_with url: posts_select_url, id: 'refresh' do |f| %>
                <%= f.select :tag, options_for_select(Post.tags.keys,@type), {} ,id: 'type-select' %>
            <% end %>
        
            <% if(@random==0)%>
                <%= link_to image_tag("/images/oreo.jpg"), "https://www.amazon.co.jp/gp/product/B079QL7GJF?pf_rd_r=76HWERK22027RGTHSFDR&pf_rd_p=3d322af3-60ce-4778-b834-9b7ade73f617" %>
            <% else %>
                <%= link_to image_tag("/images/noir.jpg"), "https://www.amazon.co.jp/%E3%83%A2%E3%83%B3%E3%83%87%E3%83%AA%E3%83%BC%E3%82%BA%E3%83%BB%E3%82%B8%E3%83%A3%E3%83%91%E3%83%B3-3490117-%E3%83%8A%E3%83%93%E3%82%B9%E3%82%B3-%E3%82%AA%E3%83%AC%E3%82%AA%E3%83%90%E3%83%8B%E3%83%A9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%A0-18%E6%9E%9A%C3%9710%E7%AE%B1/dp/B01KNI4DT2/ref=sr_1_1_sspa?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&dchild=1&keywords=%E3%82%AA%E3%83%AC%E3%82%AA&qid=1587843046&s=food-beverage&sr=1-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFQNlVLU1A5MlJJVzMmZW5jcnlwdGVkSWQ9QTEwMTA0MjhHRFM3UElROEg5N1UmZW5jcnlwdGVkQWRJZD1BMlZBOVgyNEpEVklRQSZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=" %>
            <% end %>
        </div>
        <ul>
            <% @posts.each do |post| %>
                <% if (post.tag == @type || @type == Post.tags.keys[0])&&(post.content.include?("#{@search_word}"))%>
                    <li class="post-content">
                        <a href="<%= "/posts/#{post.id}/show" %>" class="link-post">
                            <div class="content-header">
                                <object><%= link_to("/users/#{post.user.id}/show") do %><img class="icon-image" src="<%= "/images/#{post.user.icon_image}" %>"><% end %></object>
                                <div class="header-text">
                                    <span class="user-name"><%= post.user.name %></span>
                                    <p class="post-date">2020年5月23日　12:50</p>
                                </div>
                            </div>
                            
                            <div class="post-contener">
                                <div class = "post-content-body">
                                    <p class="content-text"><%= post.content %></p>
                                    <ul class="tweet-image-wrapper">
                                        <% if (post.image_1 !=nil)%>
                                            <li><a href="<%= "/images/tweet_images/#{post.image_1}" %>" data-lightbox="group"><img class="tweet-image" src="<%= "/images/tweet_images/#{post.image_1}" %>"></a></li>
                                        <% end %>
                                        <% if (post.image_2 !=nil)%>
                                            <li><a href="<%= "/images/tweet_images/#{post.image_2}" %>" data-lightbox="group"><img class="tweet-image" src="<%= "/images/tweet_images/#{post.image_2}" %>"></a></li>
                                        <% end %>
                                        <% if (post.image_3 !=nil)%>
                                            <li><a href="<%= "/images/tweet_images/#{post.image_3}" %>" data-lightbox="group"><img class="tweet-image" src="<%= "/images/tweet_images/#{post.image_3}" %>"></a></li>
                                        <% end %>
                                        <% if (post.image_4 !=nil)%>
                                            <li><a href="<%= "/images/tweet_images/#{post.image_4}" %>" data-lightbox="group"><img class="tweet-image" src="<%= "/images/tweet_images/#{post.image_4}" %>"></a></li>
                                        <% end %>
                                    </ul>
                                </div>

                                <div class="post-like-info">
                                    <% if (post.like_count > 0)%>
                                        <p><img class="btn-unlike" src="/images/ui/good2.png"><%= post.like_member_random %>さん<% if (post.like_count > 1)%>　他<%= post.like_count - 1 %>人<% end %></p>
                                    <% end %>
                                </div>
                            </div>
                        </a>

                        <div class = "post-content-footer">
                            <% if Like.find_by(user_id: @current_user.id, post_id: post.id) %>
                                <div class="footer-icon">
                                    <%= link_to("/likes/#{post.id}/#{@type}/destroy",{method: "post"}) do %>
                                        <span><img class="btn-like" src="/images/ui/good3.png">いいね</span>
                                    <% end %>
                                </div>
                            <% else %>
                                <div class="footer-icon">
                                    <%= link_to("/likes/#{post.id}/#{@type}/create",{method: "post"}) do %>
                                        <span><img class="btn-unlike" src="/images/ui/good1.png">いいね</span>
                                    <% end %>
                                </div>
                            <% end %>
                            <div class="footer-icon footer-comments">
                                <%= link_to("/posts/#{post.id}/new") do %>
                                    <span><img class="btn-like" src="/images/ui/comment.png">コメント</span>
                                <% end %>
                            </div>
                        </div>
                    </li>
                <% end %>
            <% end %>
        </ul>
    </div>
</div>

<script>
    $(function(){
        $("#type-select").change(function(){
            $("#refresh").submit();
        });
    });
</script>

app/views/posts/new.html.erb
<div class="main post-wrapper">
    <%= form_for @post do |f| %>
        <div class="field">
            <%= f.text_area :content, size: "30x10" %>
            <%= f.select :tag, Post.tags.keys.to_a, {} %>
            <label>画像1</label>
            <%= f.file_field :input_image_name_1 %>
            <label>画像2</label>
            <%= f.file_field :input_image_name_2 %>
            <label>画像3</label>
            <%= f.file_field :input_image_name_3 %>
            <label>画像4</label>
            <%= f.file_field :input_image_name_4 %>
            <%= f.submit "ツイートする",  class: "btn btn-primary btn-lg"%>
        </div>
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="post-content">
    <div class="content-header">
        <object><%= link_to("/users/#{@post.user.id}/show") do %><img class="icon-image" src="<%= "/images/#{@post.user.icon_image}" %>"><% end %></object>
        <div class="header-text">
            <span class="user-name"><%= @post.user.name %></span>
            <p class="post-date">2020年5月23日　12:50</p>
        </div>
    </div>

    <div class="post-contener">
        <div class = "post-content-body">
            <p class="content-text"><%= @post.content %></p>
            <ul class="tweet-image-wrapper">
                <% if (@post.image_1 !=nil)%>
                    <li><a href="<%= "/images/tweet_images/#{@post.image_1}" %>" data-lightbox="group"><img class="tweet-image" src="<%= "/images/tweet_images/#{@post.image_1}" %>"></a></li>
                <% end %>
                <% if (@post.image_2 !=nil)%>
                    <li><a href="<%= "/images/tweet_images/#{@post.image_2}" %>" data-lightbox="group"><img class="tweet-image" src="<%= "/images/tweet_images/#{@post.image_2}" %>"></a></li>
                <% end %>
                <% if (@post.image_3 !=nil)%>
                    <li><a href="<%= "/images/tweet_images/#{@post.image_3}" %>" data-lightbox="group"><img class="tweet-image" src="<%= "/images/tweet_images/#{@post.image_3}" %>"></a></li>
                <% end %>
                <% if (@post.image_4 !=nil)%>
                    <li><a href="<%= "/images/tweet_images/#{@post.image_4}" %>" data-lightbox="group"><img class="tweet-image" src="<%= "/images/tweet_images/#{@post.image_4}" %>"></a></li>
                <% end %>
            </ul>
        </div>
    </div>

    <div class = "post-content-footer">
        <% if Like.find_by(user_id: @current_user.id, post_id: @post.id) %>
            <div class="footer-icon">
                <%= link_to("/likes/#{@post.id}/#{@type}/destroy",{method: "post"}) do %>
                    <span><img class="btn-like" src="/images/ui/good3.png">いいね</span>
                <% end %>
            </div>
        <% else %>
            <div class="footer-icon">
                <%= link_to("/likes/#{@post.id}/#{@type}/create",{method: "post"}) do %>
                    <span><img class="btn-unlike" src="/images/ui/good1.png">いいね</span>
                <% end %>
            </div>
        <% end %>
        <div class="footer-icon footer-comments">
            <%= link_to("/posts/#{@post.id}/new") do %>
                <span><img class="btn-like" src="/images/ui/comment.png">コメント</span>
            <% end %>
        </div>
    </div>
</div>

<%# リプライ %>
<% @reply_posts.each do |post| %>
    <li class="post-content">
        <a href="<%= "/posts/#{post.id}/show" %>" class="link-post">
            <div class="content-header">
                <object><%= link_to("/users/#{post.user.id}/show") do %><img class="icon-image" src="<%= "/images/#{post.user.icon_image}" %>"><% end %></object>
                <div class="header-text">
                    <span class="user-name"><%= post.user.name %></span>
                    <p class="post-date">返信先：@<%= @post.user.name %> さん</p>
                </div>
            </div>
            
            <div class="post-contener">
                <div class = "post-content-body">
                    <p class="content-text"><%= post.content %></p>
                    <ul class="tweet-image-wrapper">
                        <% if (post.image_1 !=nil)%>
                            <li><a href="<%= "/images/tweet_images/#{post.image_1}" %>" data-lightbox="group"><img class="tweet-image" src="<%= "/images/tweet_images/#{post.image_1}" %>"></a></li>
                        <% end %>
                        <% if (post.image_2 !=nil)%>
                            <li><a href="<%= "/images/tweet_images/#{post.image_2}" %>" data-lightbox="group"><img class="tweet-image" src="<%= "/images/tweet_images/#{post.image_2}" %>"></a></li>
                        <% end %>
                        <% if (post.image_3 !=nil)%>
                            <li><a href="<%= "/images/tweet_images/#{post.image_3}" %>" data-lightbox="group"><img class="tweet-image" src="<%= "/images/tweet_images/#{post.image_3}" %>"></a></li>
                        <% end %>
                        <% if (post.image_4 !=nil)%>
                            <li><a href="<%= "/images/tweet_images/#{post.image_4}" %>" data-lightbox="group"><img class="tweet-image" src="<%= "/images/tweet_images/#{post.image_4}" %>"></a></li>
                        <% end %>
                    </ul>
                </div>

                <div class="post-like-info">
                    <% if (post.like_count > 0)%>
                        <p><img class="btn-unlike" src="/images/ui/good2.png"><%= post.like_member_random %>さん<% if (post.like_count > 1)%>　他<%= post.like_count - 1 %>人<% end %></p>
                    <% end %>
                </div>
            </div>
        </a>

        <div class = "post-content-footer">
            <% if Like.find_by(user_id: @current_user.id, post_id: post.id) %>
                <div class="footer-icon">
                    <%= link_to("/likes/#{post.id}/#{@type}/destroy",{method: "post"}) do %>
                        <span><img class="btn-like" src="/images/ui/good3.png">いいね</span>
                    <% end %>
                </div>
            <% else %>
                <div class="footer-icon">
                    <%= link_to("/likes/#{post.id}/#{@type}/create",{method: "post"}) do %>
                        <span><img class="btn-unlike" src="/images/ui/good1.png">いいね</span>
                    <% end %>
                </div>
            <% end %>
            <div class="footer-icon footer-comments">
                <%= link_to("/posts/#{post.id}/new") do %>
                    <span><img class="btn-like" src="/images/ui/comment.png">コメント</span>
                <% end %>
            </div>
        </div>
    </li>
<% end %>

app/views/users/edit.html.erb
<div class="edit-wrapper">
    <%= form_with url: users_update_url ,method: :post do |f| %>
        <label>名前</label>
        <%= f.text_field :name %>
        <label>アイコン</label>
        <%= f.file_field :icon %>
        <%= f.submit "更新する",  class: "btn btn-primary btn-lg"%>
    <% end %>
</div>

app/views/users/login_form.html.erb
<header>
	<h1>ログイン</h1>
</header>
<div class="login-modal-wrapper">
    <div class="login-modal">
        <div class="input-block">
            <p class="input-title">ユーザー名</p>
            <input type="text" class ="input-text" name="userName">
        </div>
        <div class="input-block">
            <p class="input-title">パスワード<span id="note">※8文字以上必須</span></p>
            <input type="password" class ="input-text" name="password">
        </div>
        <div class="buttons">
            <button type="button" id="sign-up" class="btn btn-success btn-lg">新規登録</button>
            <button type="button" id="login" class="btn btn-primary btn-lg">ログイン</button>
        </div>
        <div class="warning" id="empty-name">ユーザー名もしくはパスワードが違います</div>
    </div>
</div>

app/views/users/signup_form.html.erb
<div class="page-title">
	<h1>新規登録</h1>
</div>
<div class="login-modal-wrapper">
    <div class="login-modal">
        <%= form_tag("/create") do %>
            <div class="input-block">
                <p class="input-title">ユーザー名</p>
                <input type="text" class ="input-text" name="name">
                <p class="input-title">パスワード<span id="note">※8文字以上必須</span></p>
                <input type="password" class ="input-text" name="password">
                <button type="submit" id="sign-up" class="btn btn-success btn-lg">新規登録</button>
            </div>
        <% end %>
        <div class="warning" id="empty-name">ユーザー名もしくはパスワードが違います</div>
    </div>
</div>